version: '3.4'

services:
  backend:
    image: backend
    container_name: backend
    build:
      context: mood-shifter-backend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production

  frontend:
    image: frontend
    container_name: frontend
    build:
      context: mood-shifter-frontend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000

  model:
    image: model
    container_name: model
    build: 
      context: mood-shifter-model
      dockerfile: ./Dockerfile